---
- name: installation and configuration of a relay email server
  hosts: email
  tasks:
  - name: installation of some packages
    yum:
      name: postfix
      state: latest
  - name: opening firewall service
    firewalld:
      service: smtp
      immediate: yes
      permanent: yes
      state: enabled
  - name: configuration of myorigin
    command: 'postconf -e "myorigin = node2.viannijeu.cm"'
  - name: configuration of realy server
    command: 'postconf -e "relayhost  = node3.viannijeu.cm"' 
  - name: configuration of destination message
    command: 'postconf -e "local_transport = error: No local delivery"'
  - name: configuration of destination
    command: 'postconf -e "destination = "'
  - name: configuration of  domain
    command: 'postconf -e "mydomain = viannijeu.cm"'
  - name: configuration of networks
    command: 'postconf -e "mynetworks = 127.0.0.1/8"'
  - name: configuration of interfaces
    command: 'postconf -e "inet_interfaces = localhost"'
  - name: configuration of protocols
    command: 'postconf -e "inet_protocols = ipv4"'
  - name: activation of service
    service:
      name: postfix
      state: restarted
      enabled: yes
